name: Multi-Platform Build Qt App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install aqtinstall (Python package)
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: pip install aqtinstall

    - name: Install Qt 6.6.1 (Windows)
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        # Используем исправленный идентификатор архитектуры: win64_mingw
        aqt install-qt windows desktop 6.6.1 win64_mingw -O $env:GITHUB_WORKSPACE/Qt
        $QT_DIR = Join-Path $env:GITHUB_WORKSPACE "Qt\6.6.1\mingw_64"
        echo "QT_DIR=$QT_DIR" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

    - name: Install Qt 6.6.1 (Linux)
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential libgl1-mesa-dev
        aqt install-qt linux desktop 6.6.1 gcc_64 -O $GITHUB_WORKSPACE/Qt
        echo "QT_DIR=$GITHUB_WORKSPACE/Qt/6.6.1/gcc_64" >> $GITHUB_ENV

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_PREFIX_PATH=${{ env.QT_DIR }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build Project
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Run windeployqt (Windows only)
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        $windeployqtPath = Join-Path $env:QT_DIR "bin\windeployqt.exe"
        cd build/Release
        & $windeployqtPath OnlyFrameWindow.exe 

    - name: Archive and Upload Artifacts (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: OnlyFrameWindow-Windows-Build
        path: build/Release/

    - name: Archive and Upload Artifacts (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: OnlyFrameWindow-Linux-Build
        path: build/
