name: Multi-Platform Build Qt App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]

    steps:
    - name: Checkout repository
      # Обновлено до v4 (или выше)
      uses: actions/checkout@v4 

    # Используем альтернативное действие для установки Qt, чтобы избежать ошибки "repository not found"
    - name: Setup Qt
      uses: jurplewa/qbuild-action@v4
      with:
        version: '6.6.1'
        arch: 'windows_amd64'

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build Project
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Run windeployqt (Windows only)
      if: matrix.os == 'windows-latest'
      run: |
        cd build/Release
        windeployqt.exe OnlyFrameWindow.exe 

    - name: Archive and Upload Artifacts (Windows)
      if: matrix.os == 'windows-latest'
      # Обновлено до v4 (или выше)
      uses: actions/upload-artifact@v4 
      with:
        name: OnlyFrameWindow-Windows-Build
        path: build/Release/

    - name: Archive and Upload Artifacts (Linux)
      if: matrix.os == 'ubuntu-latest'
      # Обновлено до v4 (или выше)
      uses: actions/upload-artifact@v4 
      with:
        name: OnlyFrameWindow-Linux-Build
        path: build/
